apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-flask
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
spec:
  selector:
    matchLabels:
      app: hello-flask
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image:  docker.io/hariprasad10/hello-flask
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000